package executor

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/nexus-dev/nexus/internal/domain"
)

// DocGenerator handles automatic documentation generation.
// Implements port.SkillExecutor for the "documentation" skill category.
// Generates a NEXUS_CONTEXT.md file in the project root with a summary
// of the active context: environment variables, CLI tools, Git branch, and skills.
type DocGenerator struct{}

func NewDocGenerator() *DocGenerator {
	return &DocGenerator{}
}

func (d *DocGenerator) Name() string {
	return string(domain.SkillCategoryDocs)
}

func (d *DocGenerator) Execute(project *domain.Project, env *domain.EnvironmentConfig, skill *domain.Skill) (*domain.SkillResult, error) {
	startTime := time.Now()

	repoDir := project.RootPath
	if repoDir == "" {
		repoDir, _ = os.Getwd()
	}

	// Resolve output filename from skill config (default: NEXUS_CONTEXT.md)
	outputFile := "NEXUS_CONTEXT.md"
	if skill.Config != nil {
		if f, ok := skill.Config["output_file"]; ok {
			if fname, ok := f.(string); ok && fname != "" {
				outputFile = fname
			}
		}
	}

	// Determine whether to include env var names
	includeEnvNames := true
	if skill.Config != nil {
		if v, ok := skill.Config["include_env_names"]; ok {
			if b, ok := v.(bool); ok {
				includeEnvNames = b
			}
		}
	}

	// Build the markdown document
	var sb strings.Builder

	sb.WriteString("# 🧩 Nexus Context Summary\n\n")
	sb.WriteString(fmt.Sprintf("> Auto-generated by Nexus on `%s`\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("---\n\n")

	// Project Info
	sb.WriteString("## 📦 Project\n\n")
	sb.WriteString(fmt.Sprintf("| Field | Value |\n"))
	sb.WriteString(fmt.Sprintf("|-------|-------|\n"))
	sb.WriteString(fmt.Sprintf("| **Name** | %s |\n", project.Name))
	sb.WriteString(fmt.Sprintf("| **Slug** | %s |\n", project.Slug))
	if project.RepoURL != "" {
		sb.WriteString(fmt.Sprintf("| **Repository** | %s |\n", project.RepoURL))
	}
	sb.WriteString(fmt.Sprintf("| **Environment** | %s |\n", env.Name))
	if env.Branch != "" {
		sb.WriteString(fmt.Sprintf("| **Git Branch** | `%s` |\n", env.Branch))
	}
	sb.WriteString("\n")

	// Environment Variables
	if includeEnvNames && len(env.EnvVars) > 0 {
		sb.WriteString("## 🔐 Environment Variables\n\n")
		sb.WriteString("| Variable | Status |\n")
		sb.WriteString("|----------|--------|\n")

		keys := make([]string, 0, len(env.EnvVars))
		for k := range env.EnvVars {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, k := range keys {
			sb.WriteString(fmt.Sprintf("| `%s` | ✅ configured |\n", k))
		}
		sb.WriteString("\n")
	}

	// CLI Profiles
	if len(env.CLIProfiles) > 0 {
		sb.WriteString("## ⚡ CLI Profiles\n\n")
		sb.WriteString("| Tool | Account | Region |\n")
		sb.WriteString("|------|---------|--------|\n")
		for _, p := range env.CLIProfiles {
			region := p.Region
			if region == "" {
				region = "—"
			}
			sb.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", p.Tool, p.Account, region))
		}
		sb.WriteString("\n")
	}

	// Active Skills
	enabledSkills := project.GetEnabledSkills()
	if len(enabledSkills) > 0 {
		sb.WriteString("## 🧩 Active Skills\n\n")
		sb.WriteString("| Skill | Category | Priority |\n")
		sb.WriteString("|-------|----------|----------|\n")
		for _, s := range enabledSkills {
			sb.WriteString(fmt.Sprintf("| %s | `%s` | %d |\n", s.Name, s.Category, s.Priority))
		}
		sb.WriteString("\n")
	}

	// Hooks
	if len(env.Hooks) > 0 {
		sb.WriteString("## 🪝 Script Hooks\n\n")
		sb.WriteString("| Name | Phase | Command |\n")
		sb.WriteString("|------|-------|---------|\n")
		for _, h := range env.Hooks {
			sb.WriteString(fmt.Sprintf("| %s | `%s` | `%s` |\n", h.Name, h.Phase, h.Command))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n")
	sb.WriteString("*This file is regenerated on every `nexus switch`. Do not edit manually.*\n")

	// Write the file
	outputPath := filepath.Join(repoDir, outputFile)
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return &domain.SkillResult{
			SkillName: skill.Name,
			Status:    domain.SkillStatusFailed,
			Message:   fmt.Sprintf("Failed to write %s: %v", outputFile, err),
			Duration:  time.Since(startTime),
			Error:     err,
		}, nil
	}

	return &domain.SkillResult{
		SkillName: skill.Name,
		Status:    domain.SkillStatusSuccess,
		Message:   fmt.Sprintf("Generated %s with project context", outputFile),
		Duration:  time.Since(startTime),
		Actions:   []string{fmt.Sprintf("Wrote %s", outputPath)},
	}, nil
}

func (d *DocGenerator) Rollback(project *domain.Project, env *domain.EnvironmentConfig) error {
	// Could delete the generated file, but it's harmless
	return nil
}
